### ISSUE TITLE
Note which cards player actually got to play, in addition to sending the whole deck

### ISSUE THREAD

**Issue by shawkinsl** [mtgatracker/mtgatracker#108]
inspired by https://www.reddit.com/r/MagicArena/comments/8b9com/track_datawins_with_google_sheets/

**Comment by kealdor** [comment]
this was requested in discord this morning again by 'Rick' - he uploaded a screenshot of what he was refering to in the general channel - https://cdn.discordapp.com/attachments/425145310684250114/450950437638504458/PHOTO.jpg

**Comment by shawkinsl** [comment]
Note: this says "instead of," but really should be "in addition to." Updating the title

**Comment by shawkinsl** [comment]
Should also calculate the percent of played cards that were lands, so we can check if a game was screwed or flooded

**Comment by emerald000** [comment]
It would be much better if we create an hypergeometric distribution using the total number of lands in the deck, the number of cards in the deck and the number of cards drawn. You can then calculate the probability of drawing at least/at most the number of lands that were drawn.

For example, if you draw 8 lands in 12 cards in a 26 lands deck (with 60 cards), you get P(X≥8) = 6.75%. Which means in 6.75% of games, you will draw at least 8 lands in 12 cards with that deck.
