### ISSUE TITLE
Handle if there is already a server or client running

### ISSUE THREAD

**Issue by shawkinsl** [mtgatracker/mtgatracker#14]

**Comment by kealdor** [comment]
for MTGA or for Tracker itself? the code below can be adjusted to do either

+from sys import platform as _platform
+import subprocess
+import psutil

+#Close The Exe's when needed
+n = 0 # number of instances of the program running 
+
+prog = [line.split() for line in subprocess.check_output("tasklist").splitlines()]
+prog.pop(e) for e in range(3)]
+
+for task in prog:
+    if task[0]=="MTGA.exe":
+      n = 1
+      
+    if n > 0:
+      return True
+   
+    if n == 0:
+         if _platform == "win32" or _platform == "win64":
+            os.system("TASKKILL /F /IM MTGATracker.exe")
+         
+         #if _platform == "linux" or _platform == "linux2" or _platform == "darwin":
+            #for pid in (process.pid for process in psutil.process_iter() if process.name()=="MTGATracker.exe"):
+               #os.kill(pid)
