### ISSUE TITLE
Option to turn off tracker mode

### ISSUE THREAD

**Issue by shawkinsl** [mtgatracker/mtgatracker#155]
Requested by [Uber_Jester](https://www.twitch.tv/uber_jester): a mode to turn off tracking and instead just keep up the initial list of cards in the deck. Should be settable in the settings panel.

**Comment by kealdor** [comment]
this is done already so id like to hit close on it

**Comment by shawkinsl** [comment]
Er, this is not done

**Comment by kealdor** [comment]
oh my bad i misread it i thought it meant reporting at first
