### ISSUE TITLE
Report overall winrate to inspector

### ISSUE THREAD

**Issue by shawkinsl** [mtgatracker/mtgatracker#176]
Reported by heksiu in discord:

Inspector should report two metrics:

1) The overall winrate that _arena_ is logging, and 
2) The overall winrate for whatever filter you're currently showing in inspector

The difference between 1) and 2) (with no filter) will show how effective you are at remembering to start the tracker, or maybe alternatively how reliably the tracker is making contact with inspector if you absolutely never forget.

**Comment by kealdor** [comment]
by winrate do you mean the actual win loss records? if so i have that going into the Account Summary Page i was making :)

**Comment by shawkinsl** [comment]
Unfortunately, it looks like this was removed from the logs :(
