### ISSUE TITLE
Add minimize and close buttons

### ISSUE THREAD

**Issue by shawkinsl** [mtgatracker/mtgatracker#177]
Reported by heksiu on discord.
This is pretty basic functionality. We should have it. (being frameless is no excuse!)

**Comment by jnovack** [comment]
I feel this is "why"?

* Click on the EyeSlash. Window visible, but tiny as possible.
* Right-Click Window -> Minimize = Minimized.
* Right-Click Window -> Close = Close

How quickly do you need the application closed that the main screen has to be cluttered with more icons?

**Comment by shawkinsl** [comment]
It's less of a matter of speed and more a matter of general user confusion. We get asked fairly frequently how to close or minimize the program, because it doesn't adhere to the UX standard of having a minimize and a close button.
