### ISSUE TITLE
"roll-up" hide mode

### ISSUE THREAD

**Issue by shawkinsl** [mtgatracker/mtgatracker#193]
Hide mode should be configurable in settings between the current "transparent" mode, and a new "roll up" mode. In "roll up" mode, the tracker should, like it says, "roll up," so that clicks can be sent behind the tracker. (jquery `slideUp` ?)

**Comment by RAMunch** [comment]
When this is implemented it would be nice to have an auto roll up when not in match feature.
When it detects match start roll down, roll up at end.

Currently the invisible window gets in the way of deck editor and causes it to act odd. The roll up would fix that.
