### ISSUE TITLE
Handle games where viewer is not the hero more gracefully

### ISSUE THREAD

**Issue by shawkinsl** [mtgatracker/mtgatracker#198]
Reported by bcsj in discord:

Whenever there is a game visible in inspector that is not owned by the viewer, the viewer will be logged out if they try to click on game details, since they don't "own" it. Access permissions per game need to be modified to allow hero or opponent, but obscure hero deck name & hero deck contents if the viewer is the opponent, not the hero.

**Comment by Gaelan** [comment]
Would also be cool to have an opt-in option to show decks to opponents in inspector
