### ISSUE TITLE
Three card ids missing

### ISSUE THREAD

**Issue by rrwoods** [mtgatracker/mtgatracker#307]
Card IDs 69449, 69450, and 69451 are present in my MTGA collection log, but are unrecognized when I try to pull them from the mtga module using all_mtga_cards.find_one or .search .  I suspect that these are associated with the three planeswalkers given to closed beta participants, but I can't be sure.

**Comment by shawkinsl** [comment]
Thanks for the report! I suspect you're correct. I'll check in the unit resource files sometime this weekend, and I'd expect a python-mtga + node-mtga update by Monday at the latest

**Comment by rrwoods** [comment]
Sweet!  Thanks for the hard work :)

**Comment by shawkinsl** [comment]
Confirming these are the ID's, good hunch!. Will have updated mtga & node packages within the hour.

69449 = loc 273049 = "Ral, Izzet Viceroy"
69450 = loc titleId 273097 = "Vraska, Golgari Queen"
69451 = loc titleId 227513 = "Teferi, Hero of Dominaria"

**Comment by shawkinsl** [comment]
https://pypi.org/project/MTGA/0.4.1/ :)

**Comment by rrwoods** [comment]
Sweet, I just pulled it with a pip install --upgrade, works like a charm!
