### ISSUE TITLE
Make sure that the values in tracker-id and tracker-id-token match

### ISSUE THREAD

**Issue by shawkinsl** [mtgatracker/mtgatracker#311]
I have a suspicion that there is some code flow that might cause a tracker-id-token to be saved, but not the tracker-id. This could cause the "authorize" button to authorize a key that isn't actually associated with any records.

https://github.com/mtgatracker/mtgatracker/blob/master/electron/main.js#L42

**Comment by IamRaviTejaG** [comment]
@shawkinsl Can you please elaborate a bit more on this issue?! I'd like to work on this issue.

**Comment by shawkinsl** [comment]
Sure! Don't forget that October is #hacktoberfest, so you may want to wait a day to submit any pull requests, u suppose depending on your timezone :)

The value stored at `tracker-id` is a plain-text unique key. The value stored at `tracker-id-token` is the string representation of a jwt that includes the same `tracker-id` string as part of it's claims along with some other data. Immediately after the line linked above, the program should decode the jwt and check if the claim in the jwt matches the `tracker-id` value retrieved immediately above the line linked above. If it matches, all is well. If it doesn't match, it should fetch a new token from the server and overwrite the `tracker-id-token` value.

It won't let me assign this issue to you, but i'll consider it claimed.

**Comment by shawkinsl** [comment]
Also, I'm guessing you're here for hacktoberfest and not MTGA, which is awesome, welcome! Note that you definitely don't need to play MTGA to solve this issue, but if you're into CCG's (like Hearthstone), you should give it a shot! It's a great game!

**Comment by shawkinsl** [comment]
@IamRaviTejaG still trying to work on this one? Anything else I can help with? This issue is currently affecting a couple users, would love to get the fix out in the next release :)

**Comment by shawkinsl** [comment]
Awesome! If you want, you find me in [our Discord](https://discord.gg/Ygfv25w) if you need real-time help :)
