### ISSUE TITLE
MTGATracker: (In) Deck Sort Order

### ISSUE THREAD

**Issue by jnovack** [mtgatracker/mtgatracker#365]
The game sorts by "Cost (Asc) -> Color (Asc) -> Name (Asc)"

![image](https://user-images.githubusercontent.com/387006/47623862-7aab8c00-daec-11e8-8537-2358321ba9b0.png)

*( i do not know why this picture is unnecessarily large)*

Color ascending order is:

* White
* Blue
* Black
* Red
* Green
* Colorless
* Multicolor (iterates through the list, 2 multicolors before 3 multicolors, WU before RG, WUB before BRG) 

For the most part, multicolor is by FIRST color, and for tri+, they can be any order (but always sorted by FIRST color).

Except **Archades, the Strategist** (1GWU) does come before stupid **Jodah, Archmage Eternal** (1URW), but let's just assume that's just because Jodah is used to being last picked in draft, and nobody likes him.

Can the onscreen decklist be sorted the same (additionally with lands LAST)

![image](https://user-images.githubusercontent.com/387006/47624022-f65a0880-daed-11e8-9f98-97e645b7d81c.png)

**Comment by emerald000** [comment]
You might want to try the "Emerald method" sort option in the settings. It's not exactly what you are looking for but is closer than the default.

And I should really get to implement actual sorting options one of those days...

**Comment by emerald000** [comment]
That's something I quickly whipped out a while ago because I was annoyed with the default sorting.

It sorts by card type, then by CMC, then by name.

**Comment by smkiewel** [comment]
I unfortunately do not have any tri+ colored cards, but here's the order for 1 and 2 colors I have:
````
W U B R G C 
WB UB UR GB RB WU
Plains Island Swamp Mountain Forest 
(lands) WU WB UB UR RB BG RG RW GW GB
`
So it doesnt look like the wheel is respected for multicolored. If anyone can verify the missing color combos, I would be happy and will implement this sort.

Related I am about to implement something close, which is a proper wheel-based color sort. Should be done soon.

**Comment by smkiewel** [comment]
[Color sort results](https://i.imgur.com/YoVHQ9e.gifv) on max size deck with all colors I could muster. That work for you?
