### ISSUE TITLE
Please allow for extended window hiding

### ISSUE THREAD

**Issue by Looking4OffSwitch** [mtgatracker/mtgatracker#370]
I know I can _temporarily_ make the tracker window smaller (by clicking the eye icon or right-clicking) but there are times when I really want the tracker running yet don't want it taking up screen space. 

Honestly, I wish the eye-icon was "sticky" so that my choice remained preserved until I clicked it again but I doubt that functionality will change. Perhaps there could be a setting for how the eye icon works?

Thank you!

**Comment by WizardRubic** [comment]
I think you can make it sticky if I understand what you're asking for correctly. When I click they eye, it never opens up again until I click it again with the following settings(takes a restart to apply setting changes): 

[https://i.imgur.com/e6UyRvj.png](https://i.imgur.com/e6UyRvj.png)

**Comment by Looking4OffSwitch** [comment]
That is _exactly_ what I was hoping for. My apologies for not finding that option on my own.

If I'm the first person to request that it works this way I wouldn't change the default behavior.
