### ISSUE TITLE
Account locked even after updating client

### ISSUE THREAD

**Issue by Arjay0** [mtgatracker/mtgatracker#380]
On version 4.5.2 but when I click on Inspector...Authorize Inspector the page loads with a message about my account being locked. Thanks.

**Comment by shawkinsl** [comment]
Hi @Arjay0 !

Have you played a game with the latest tracker? MTGATracker determines account status by what version the last game uploaded came from. From the "what gives" docs:

> To unlock your account, simply update to the latest client, and **complete a match with it running.**

**Comment by Arjay0** [comment]
yeah, i've played several games. no change

**Comment by Arjay0** [comment]
Uninstalled and reinstalled version 4.5.1. Working now.
