### ISSUE TITLE
Game sent to Inspector

### ISSUE THREAD

**Issue by jnovack** [mtgatracker/mtgatracker#382]
Please do not tell me when it did, please only tell me when it did not.  This seems like a DEBUG level message that I'm not sure I need notification for.

Notifications [SHOULD](https://tools.ietf.org/html/rfc2119) only be actionable.

**Comment by shawkinsl** [comment]
![image](https://user-images.githubusercontent.com/1424566/47959943-eb035300-dfad-11e8-922a-e9c24ea46b7c.png)

**Comment by jnovack** [comment]
Thanks! Wasn't exactly sure what that meant.  I'll assume user error! 

Will turning it off tell me if/when a game could not be sent?

**Comment by shawkinsl** [comment]
Yep, errors will come through even with that setting turned off.

Sorry for being terse in my last comment, and thanks for helping out in our issues! I've invited you to be an @mtgatracker/collaborators :)
