### ISSUE TITLE
Green Background

### ISSUE THREAD

**Issue by Asahida** [mtgatracker/mtgatracker#384]
![screenshot_1](https://user-images.githubusercontent.com/44746010/47963778-2d25a680-e039-11e8-87b8-f8c8347f2664.png)

So I get this green background, I skimmed through the issues and didn't find this, thought i'd post it here, can't play fullscreen because of this, works otherwise xD

**Comment by jnovack** [comment]
1. Settings -> Tracker Settings -> General
2. Turn Streamer Mode Off

Please **Comment and Close** if this solves your issue.

**Comment by Asahida** [comment]
yes, that was it, tbh I have no clue why I activated streamer mode since I don't stream.

I have a question: The eye on the top of the tracker does hide it, but it reappears as soon I click anywhere else in the game window so it doesn't stay hidden. Sometimes I just want it "minimized" but still have it there, please tell me if that is possible not. Thanks a dozen for making this software otherwise, it's exactly what I was looking for 👍 

I'll close the issue when I check back, or you can go ahead and do it. Thanks again!

**Comment by WizardRubic** [comment]
Try these settings(these do require a restart to apply):
![https://i.imgur.com/e6UyRvj.png](https://i.imgur.com/e6UyRvj.png"https://i.imgur.com/e6UyRvj.png")

lmk if it works!

**Comment by jnovack** [comment]
Unfortunately, I can't close, not a member of the org here (YET!). :)

The "Hide Tracker on all Right Clicks" will prevent you from freaking out when it closes every now and again on every right click.  The Un-Hide on left clicks will prevent you from getting annoyed when you hid it and don't want it back.

The "Hide" Delay to Infinity will ensure that when you hide it, it stays hidden until you specifically unhide it.

**Comment by Asahida** [comment]
I swear I went over the settings a couple times but apparently I completely ignored that slider. It solved it for me, the hud has all the customization options I need. Keep up the good work!
