### ISSUE TITLE
Ghalta, Primal Hunger doesn't display colorless mana cost

### ISSUE THREAD

**Issue by smkiewel** [mtgatracker/mtgatracker#405]
Main: 
![ghalta-full](https://user-images.githubusercontent.com/745723/48307002-96158e80-e511-11e8-8fce-a60f619d03ca.PNG)

Minimal: 
![ghalta](https://user-images.githubusercontent.com/745723/48307005-9d3c9c80-e511-11e8-90a3-02d572cb4e92.PNG)

**Comment by smkiewel** [comment]
Don't know if this effects other cards with colorless > 9.

**Comment by jnovack** [comment]
Applied `cost-reduction` tag as well, MAY be related.  Please remove if unnecessary.

**Comment by shawkinsl** [comment]
heh, cost reduction was a tag I made for like, AWS costs. I guess it works here too though ;)

**Comment by smkiewel** [comment]
Note: I was not in game when this occurred.

**Comment by shawkinsl** [comment]
It _could_ matter. (We had a display issue for split mana costs, but only in game (or maybe vice-versa), because the html doesn't DRY, i.e. it does repeat itself). Good info to have, either way.

**Comment by shawkinsl** [comment]
Oh, maybe this is because the mana font we use doesn't have a "10" icon. sigh.

**Comment by smkiewel** [comment]
> Oh, maybe this is because the mana font we use doesn't have a "10" icon. sigh.

That is exactly the thing I was thinking. And why I said I didn't know if it effected other colorless > 9.

**Comment by smkiewel** [comment]
Actually, font allows for values up to 19 (currently, easily extended). Problem was checking for length of value to be one to show, so anything greater than 9 wouldn't show up.

**Comment by smkiewel** [comment]
And fixing it breaks split cards. A new algo to determine showing needs to be figured out. Working on it.
