### ISSUE TITLE
Add hide mode toggle-only 

### ISSUE THREAD

**Issue by smkiewel** [mtgatracker/mtgatracker#417]
Add ability to make hide mode toggle-only, disabling the timer.

**Comment by smkiewel** [comment]
So I was going to write this and was reading the code and went "Hey, this should already be doing that!" And sure enough it is. And I'm pretty sure I tried to do it the right way before, but maybe not. In any event, if I am not perceptive enough sometimes to find this, maybe others aren't either. So I've added a sentence to be explicit about it. 

[my fork](https://github.com/smkiewel/mtgatracker/tree/add_hide_mode_toggle_only)

**Comment by WizardRubic** [comment]
Yeah I've seen several issues about the sliders. I didn't know I could do it either till I saw it in the code :p I guess maybe it could be worth changing all the sliders to reflect ranges since there's a few throughout the settings
