### ISSUE TITLE
In-game (drawStats) sort doesn't sort by name

### ISSUE THREAD

**Issue by smkiewel** [mtgatracker/mtgatracker#418]
Frequency
![bad-freq-sort](https://user-images.githubusercontent.com/745723/48529709-57aa0780-e862-11e8-968d-2bd909a90648.PNG)

Emerald
![bad-emerald-stats-sort-not-freq](https://user-images.githubusercontent.com/745723/48529258-406a1a80-e860-11e8-9b03-dbacd83ee24f.PNG)

Color
![bad-color-sort](https://user-images.githubusercontent.com/745723/48529546-93909d00-e861-11e8-9b27-6449a481a7fd.PNG)

Freq sub Emerald
![bad-emerald-stats-sort](https://user-images.githubusercontent.com/745723/48529106-ac984e80-e85f-11e8-96e3-12b95778bdcc.PNG)

Freq sub Color
![bad-freq-color-sort](https://user-images.githubusercontent.com/745723/48528832-96d65980-e85e-11e8-9b08-d00e7280b0d6.PNG)

Other decklist view working.

**Comment by shawkinsl** [comment]
Oops. @smkiewel if you put strings like "closes #418" in commit messages, github will automatically close out issues when the PR merges :)
