### ISSUE TITLE
After sorting the cards by draw chance is done before merging duplicate cards in the tracker

### ISSUE THREAD

**Issue by axlan** [mtgatracker/mtgatracker#429]
Shown here in this example:
![image](https://user-images.githubusercontent.com/2177458/48679021-c11a6680-eb3f-11e8-9952-b17e18b39c74.png)

It would make more sense to sort after merging duplicates

**Comment by axlan** [comment]
Hunh, it looks like the code is written to do that:
https://github.com/mtgatracker/mtgatracker/blob/master/electron/index.html#L66
I'll look at why it's not working as expected.

**Comment by axlan** [comment]
Hunh found a related issue. If you:
1. view a deck with duplicates
2. view a different deck
3. view the first deck with duplicates again

You get a bug where the duplicates get added twice. In the example I showed above the Llanowar Elf count would be shown as 6.

**Comment by smkiewel** [comment]
... and I should have noticed you put in a PR to fix this. Looks good, but if we're going to be messing with the merge decklist code, we need to unify those functions. There is no reason for those functions to be separate. It's on my 'clean up the code' list, but this is a good excuse to do it.
