### ISSUE TITLE
Overlay looks broken on Windows 7

### ISSUE THREAD

**Issue by marlonrichert** [mtgatracker/mtgatracker#433]
<img width="1440" alt="screen shot 2018-11-21 at 20 50 05" src="https://user-images.githubusercontent.com/644725/48862447-15874580-edcf-11e8-9f1d-ea00b37645a4.png">
<img width="1440" alt="screen shot 2018-11-21 at 20 52 05" src="https://user-images.githubusercontent.com/644725/48862541-54b59680-edcf-11e8-81dc-3ce6bec10197.png">
<img width="1440" alt="screen shot 2018-11-21 at 20 55 55" src="https://user-images.githubusercontent.com/644725/48862743-e1605480-edcf-11e8-94af-8d9da4d8280a.png">

**Comment by marlonrichert** [comment]
Updated to 5.0.5. Still looks very broken: <img width="1440" alt="screen shot 2018-12-27 at 14 55 29" src="https://user-images.githubusercontent.com/644725/50480916-7bc34180-09e7-11e9-8e21-1553b3b04fa3.png">

**Comment by riQQ** [comment]
It works for me on Windows 7, so it has to be some setting or a system property that is different.
