### ISSUE TITLE
Collection Window

### ISSUE THREAD

**Issue by smkiewel** [mtgatracker/mtgatracker#453]
Make Collection its own window. Add inventory tracking (gold, gems, wildcards). 

![boosters](https://user-images.githubusercontent.com/745723/49911948-561a3200-fe56-11e8-8c6c-2b2936def9df.PNG)
![collection 2](https://user-images.githubusercontent.com/745723/49341642-8bd14680-f61e-11e8-9de7-95b85e68eb8f.PNG)

[@My fork](https://github.com/smkiewel/mtgatracker/tree/collection_window)

Still pounding on it, hoping to solve #345 / #383, but that certainly shouldn't stop it from being merged.

Running list of what has been positively identified as updated by inventory changes in game:

Type | Total | Gained | Spent | Net
------|------|----------|-------|-----
Gold |X|X|X|X
Gems|X|X|X|X
Common |X|X|X|X
Uncommon |X|X|X|X
Rare|X|X|X|X
Mythic |X|X|X|X
GRN |X|X|X|X
M19 |X|X|X|X
DOM |X|X|X|X
RIX |X|X|X|X
XLN |X|X|X|X

**Comment by smkiewel** [comment]
And I totally got #345 / #383 fixed.

**Comment by smkiewel** [comment]
Now I got it. Had to do some really heavy-handed, ugly work to make rivets forget the old stuff, but it's working.

**Comment by smkiewel** [comment]
> Hello, is that possible to have the collection tracking the **Color**?

Not sure what you mean by that.

**Comment by GoldMath** [comment]
> Not sure what you mean by that.

Each **Set** have **Rarity** _(Rares, Commons,..)_ and **Color** _(Red, White, Green,...)_ cards.

Actually the Collection system only track Rarity. 
It's possible to add Color to the tracking? _(example: 23/56 White in the Core Set 2019)_

**Comment by smkiewel** [comment]
That seems a little overkill to me. I'm not sure how many people would be interested in that granularity, nor do I see off-hand the decisions it helps you make. But I freely admit, I overlook use-cases. And if you submit it, we'll definitely look at merging it.

**Comment by smkiewel** [comment]
Added booster pack tracking (not yet pushed).

![boosters](https://user-images.githubusercontent.com/745723/49911948-561a3200-fe56-11e8-8c6c-2b2936def9df.PNG)

**Comment by smkiewel** [comment]
Oh, and before I get the "why track X?", I started with only wanting to track gold, but the data was available for all the rest, so it made sense to present that data.
