### ISSUE TITLE
Remove Incognito mode toggle; update privacy policy for 5.0.0

### ISSUE THREAD

**Issue by Xenira** [mtgatracker/mtgatracker#457]
As the inspector is now local the privacy setting seems to be outdated / insufficient.

Currently the message looks like this:
> **Warning**: with incognito mode enabled, MTGATracker will not send any game data to MTGATracker services, including Inspector. This means that the Inspector will no longer work.

But the Inspector still works as its now local.

- [ ] Update description as Inspector now works with incognito mode enabled.
- [ ] Optional / Needs discussion: Add a disable option or more granular privacy controlls

Tested on: 5.0.2

**Comment by shawkinsl** [comment]
Thanks for pointing this out! You're correct that the incognito mode option is definitely confusing given that [inspector is now completely offline](https://blog.mtgatracker.com/mtgatracker-five-point-o), and probably should have been removed before 5.0.0 went out.

I'm going to consider this ticket as the tracker for 1) updating the privacy policy and 2) removing the incognito toggle altogether.
