### ISSUE TITLE
Inspector: Game history pagination failing

### ISSUE THREAD

**Issue by Slanman3755** [mtgatracker/mtgatracker#461]
Every page of game history is the same as the first page in my inspector.  Restarting the game does not help.

**Comment by shawkinsl** [comment]
Thanks for the report. Closing this as duplicate of #458. This was fixed in #455, but has not yet been released

**Comment by shawkinsl** [comment]
I just released 5.0.3 as a pre-production release with the fix for this issue, check it out on the releases page.

**Comment by Slanman3755** [comment]
Sorry I didnt search closed issues! :p
