### ISSUE TITLE
Double-faced rare cards count multiple times towards missing collection

### ISSUE THREAD

**Issue by shawkinsl** [mtgatracker/mtgatracker#499]
![image](https://user-images.githubusercontent.com/1424566/52145932-3366f700-2617-11e9-9325-b49fe2331e02.png)

Related to node mtga module, which will need some way to note if a card is double sided, so the progress calculator can know as well.

**Comment by leestran1995** [comment]
I'm new around these parts but I'd love to dive into this when I get a chance tomorrow!

**Comment by leestran1995** [comment]
Wow! Thanks for the pointers on where to start! 

After poking around a bit I have great news, the json that the scripts are parsing (referenced [here](https://github.com/mtgatracker/python-mtga/blob/efee9148f50d1bee3f5577f9879b3bd9b452a3b8/script/generate_set_map.py#L19)) includes an "isCollectible" flag! Seen here for Explosion // Expansion 
![image](https://user-images.githubusercontent.com/41343559/52180316-71e0eb00-27aa-11e9-9730-b7ed6a826c2f.png)

So (assuming the JS generation script does in fact work) we should be able to pull that from the JSON when we first parse through it and pass it along so it ends up in the final card list, and add the check to collectionRenderer.js.

I'll start working on it!

**Comment by shawkinsl** [comment]
Whoops, probably should have warned you: this is going to involve publishing packages to pypi and npm, so I also started working on it this morning: https://github.com/mtgatracker/python-mtga/commit/9d0c861618fb5cb3a7214aed3855e24c8da95cf7 . Want to double check this while I generate the JS changes?

**Comment by leestran1995** [comment]
I'm not exactly sure how to publish packages to pypi and npm so I guess it's good you took the reins! I'll keep an eye on everything (and I'm also online in the discord) and see if there's anything else I can take a stab at

**Comment by shawkinsl** [comment]
Publishing isn't hard, but it required my password ;)

npm package is published at 1.3.4. I'm going to take a break and eat something, if you want to play around with it and see if you can get the tracker changes in!

**Comment by shawkinsl** [comment]
oh, you might also need the pypi package, so it is also now uploaded at 0.5.5

**Comment by shawkinsl** [comment]
fixed in #500
