### ISSUE TITLE
Incorrect calculation of needed cards to create a deck

### ISSUE THREAD

**Issue by Ramadas108** [mtgatracker/mtgatracker#505]
It shows that I don't need to craft any cards:

https://photos.app.goo.gl/mhD8gj2yWPvgxCPD8

but then it tells me it needs 9 cards:

https://photos.app.goo.gl/bsZk5gWEuZg84amu8

**Comment by shawkinsl** [comment]
Howdy, you've reached the wrong project. This repo is for... well, mtgatracker/mtgatracker, not MTGArena pro.
