### ISSUE TITLE
3/27 update breaks MTGA tracker

### ISSUE THREAD

**Issue by thisguy23** [mtgatracker/mtgatracker#508]
3/27 update breaks MTGA tracker.. no functionality

**Comment by pcjr** [comment]
Seeing lots of errors in the debug log.

**Comment by kealdor** [comment]
Any upload any of the problem logs yet?

**Comment by pcjr** [comment]
Collection view during drafting seems to still work.

**Comment by mbaggott** [comment]
Yes broken for me too, wins and losses no longer being recorded after yesterdays update. Am happy to provide my logs if you need them.

**Comment by shawkinsl** [comment]
Fixed in 8811fbc629abfe0e62e0213dbf31d608cff8e18e, 5.2.0 will be rolling out shortly

**Comment by kealdor** [comment]
Please do they never hurt to have when trying to see exactly what went
wrong and why

**Comment by shawkinsl** [comment]
We don't require logs for this issue, but thank you. I also do not recommend uploading arena logs to the public without scrubbing specific info from them; sending them privately to sources you trust is generally a better idea.

**Comment by mbaggott** [comment]
ok thanks @shawkinsl , i did not know that. And thanks for the update, all working again here
