### ISSUE TITLE
MD5 hashes in downloads

### ISSUE THREAD

**Issue by Dragas** [mtgatracker/mtgatracker#511]
Yo!

In releases page, you're using only MD5 hashes to confirm that it is indeed the file you intend people to download. Mind you MD5 is prone to collision attacks and should not be used to confirm file integrity. Do you mind adding SHA1 and SHA256 signatures to the downloads page?

**Comment by shawkinsl** [comment]
Added sha256 to this release manually, and added it to the deployment script. Thanks!
