### ISSUE TITLE
Need a way to reset session data

### ISSUE THREAD

**Issue by scottchiefbaker** [mtgatracker/mtgatracker#515]
The session counter is active as long as the MTGATracker is running. The problem is, that I don't close it very often and the session data ends up being semi-meaningless. If I leave MTGATracker open over night the "session" isn't really the length of the time the program is open. I propose two potential solutions:

* The session data should automatically reset after a specific time period
  * Every night at midnight
  * After X hours (6?) of non-activity between games
* As part of menu option after right-click

**Comment by gotoariel** [comment]
If you go into the Settings menu there's a section called "Session Win/Loss Counters" that should allow you to reset or even adjust the session counters as you see fit. Would this work for you?

**Comment by scottchiefbaker** [comment]
Ah... I didn't know that setting was there. Yes that will work. I do think it would be a good idea for MTGATracker to be a little "smarter" and automatically reset the session counter after X hours of non-use. This is good enough for now.
