### ISSUE TITLE
Tracker no longer works as of May 2020 update - log file name?

### ISSUE THREAD

**Issue by dglynch** [mtgatracker/mtgatracker#533]
As of the May 2020 update, the tracker no longer works. I suspect this may be related to the renaming of the log file. However, even when I updated the log file location in the Settings page (and restarted the tracker as directed), the tracker still did not work.

**Comment by kealdor** [comment]
coding might possible be looking explicitly for  for 'outputlog.txt' ? is
my best assumption from when i last got to contribute to the project a
while ago

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by quadvirgo** [comment]
Looks like WotC changed the name of the output logs, according to the patch notes:

OUTPUT LOGS
The file name for output_log.txt has changed to Player.log
The location of the file has not changed; assuming default installation, the file is located here: \ . . .\AppData\LocalLow\Wizards of The Coast\MTGA\Player.log
Output logs will also save the log from your previous session (Player-prev.log)
Additional initial tracking support for player draft.
Developer Note: Operative word ‘initial’. We’re already looking at ways to expand what information is being tracked.

**Comment by ScepticDope** [comment]
_Until this gets updated you can get the tracker to work again for now by using a symlink to the file._

Remove the deprecated `output_log.txt` then create a symlink. On Windows you can do that using the following in a admin cmd:

`cd C:\Users\*your_username*\AppData\LocalLow\Wizards Of The Coast\MTGA`

`mklink output_log.txt Player.log`

Good luck!

**Comment by quadvirgo** [comment]
I tried to do this, but I received an error message: "You do not have
sufficient privilege to perform this operation."

**Comment by ScepticDope** [comment]
@quadvirgo 

> admin cmd

GL ;)

**Comment by quadvirgo** [comment]
Hmm, I got the admin cmd to work, but the tracker is still not working :(

**Comment by ScepticDope** [comment]
> 
> 
> Hmm, I got the admin cmd to work, but the tracker is still not working :(

Did you follow the instructions to a tee? Remove the `output_log.txt` first and make sure to replace:

> *your_username*

Its working for me like this without but, maybe try a restart?

**Comment by quadvirgo** [comment]
I think I did. Here is what I did. I went to the file/directory location you described, using my username, I deleted the output_log.txt file from that location. Then, I opened up CMD in Admin mode by right-clicking on it. I copy/pasted the two lines, with my user name replaced. This time, I did not receive an error as before. 

I brought up the tracker as usual before I started MTGA. Played a game, and the MTGATracker did not show my deck name. I lost a game, it didn't show the loss under Settings > Win/Loss Counters. Then I played a second game, won that game with the same deck, and the tracker still showed the main screen, no deck name, no win counter. 

If I restart the PC, will I need to repeat the steps above?

**Comment by ScepticDope** [comment]
@quadvirgo If you open the admin CMD in the right location you only need to use the second command, the cd command is just to set the proper location for the second command.

Try the following. Permanently delete the new `output_log.txt`  or delete it and clear your bin. Do a restart. Retry to create the symlink. Check if you have a new `output_log.txt` now. If the `output_log.txt` never gets created you might need to check if you have the privilege to create symlinks on your system.

After the symlink file is created, first start the tracker then start Magic Arena, if its still not working I have no idea whats going on.

**Comment by dglynch** [comment]
I've also had no luck trying the workaround describe above.

**Comment by dglynch** [comment]
After reading some comments on the Discord, I found a workaround that works for me. You don't need to create a symlink. Instead, just configure the log location to the new file name in Settings, and then ensure you always start Arena **before** starting MTGATracker. That's all that's needed. If you start Arena while MTGATracker is already running, the log file will be deleted and recreated by Arena and this will stop MTGATracker from reading it.

**Comment by quadvirgo** [comment]
It is working again! I tried both solutions, from ScepticDope and dglynch; so I'm not sure which one worked. I'm just thankful it's working again, thank you :)
