### ISSUE TITLE
macOS beta 6.2.0: Empty Terms of Service

### ISSUE THREAD

**Issue by javydreamercsw** [mtgatracker/mtgatracker#548]
Getting an empty term of service screen I can't get past.

<img width="798" alt="Screen Shot 2022-01-20 at 11 26 34 AM" src="https://user-images.githubusercontent.com/2817343/150390436-e528126e-188d-48b6-8aa8-391e9ab19875.png">

MacOS 10.15.7

**Comment by satorielectronics** [comment]
having the same issue!

![Screen Shot 2022-02-22 at 8 32 57 AM](https://user-images.githubusercontent.com/11412521/155153350-c1d06c78-9251-48bf-97de-2b8a0b717918.png)

**Comment by Lohoris** [comment]
Same here, on Mac OS 11.6.5

**Comment by rodrigovsilva** [comment]
Same here. Monterey 12.3.1

**Comment by RdHamilton** [comment]
I can a test that this issue is currently still occurring.

**Comment by jvargas2** [comment]
Still happening on Mac OS 12.5.1.

**Comment by driftSam** [comment]
Same issue here. Mac OS 12.2.1

**Comment by jacksonofalltrades** [comment]
It's been over a year since this was reported, is someone ever going to fix this?

**Comment by tsroten** [comment]
Just ran into this issue as well. You can get around it by editing the file `~/Library/Application Support/mtgatracker/Settings` and adding this to the `tosAcks` setting: `"68c0638dcea3ee8e3236cfa98892e1ac"`.

1. Open Finder
2. In the menu bar click `Go` > `Go to Folder...`
3. Paste `~/Library/Application Support/mtgatracker` and hit enter.
4. Right click on `Settings` and click Open With TextEdit.app
5. Change the first part from this:
```
{"tosAcks":[],
```
6. To this:
```
{"tosAcks":["68c0638dcea3ee8e3236cfa98892e1ac"],
```
7. Save the file.
8. Reopen MTGATracker
