### ISSUE TITLE
Aftermath card IDs

### ISSUE THREAD

**Issue by med200** [mtgatracker/mtgatracker#96]
I don't know if this actually affects anything right now but the IDs for aftermath cards are slightly off. MTGATracker currently has two IDs for each aftermath cards - the first half at ID `n` and the second half at ID `n+3`. For example you have Consign at 65779 and Oblivion at 65782. MTG Arena actually has three IDs for each aftermath card: one for the full card you put in your deck with ID `n` (eg. "Consign /// Oblivion", 65779), then the first half with ID `n+2` (Consign, 65781), and the second half with ID `n+4` (Oblivion, 65783).

You can verify this by importing a decklist such as:
~~~~
1 Consign /// Oblivion (HOU) 149
1 Consign (HOU) 149a
1 Oblivion (HOU) 149b
~~~~
You get this in the client:
![aftermath](https://user-images.githubusercontent.com/2227439/38264843-463faf30-3742-11e8-92be-81300e5110f1.png)
And in the output log:
~~~~
"mainDeck": [
      {
        "id": "65779",
        "quantity": 1
      },
      {
        "id": "65781",
        "quantity": 1
      },
      {
        "id": "65783",
        "quantity": 1
      }
    ],
~~~~
The other aftermath cards in AKH and HOU all follow the same pattern and there appear to be no weird ID jumps among them.

**Comment by shawkinsl** [comment]
Whoa, great find! I will be honest, I totally just guessed n+3 for aftermath ID's, and it seemed to work well enough, so I just left it alone. I'll see if I can get this information clearly recorded in the code here though, I don't want MTGATracker to be a source of incorrect data.

Thanks! This is great info!
