### ISSUE TITLE
import structure needs more sanity

### ISSUE THREAD

**Issue by shawkinsl** [mtgatracker/mtgatracker#99]
Was trying to do a pretty simple task with set_data, but find myself completely unable to because of this crazy rat's nest of imports (hooray, python). This has so far been unstructured (it works, ship it), and definitely needs to be revisited.

**Comment by kealdor** [comment]
i noticed this to like the core of the program is spread across like 10 python files which seem to depend on each other

**Comment by shawkinsl** [comment]
Heh, closing this since we've now published python-mtga and node-mtga
